apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
      - name: game-app
        image: harsha6798/devsecops-game:11harsha6798/devsecops-game:5
        ports:
        - containerPort: 8080